sudo: false

language: node_js

services:
  - docker

node_js:
  - '8'

install:
  - npm i
  - npm i coveralls

script:
  - npm run lint
  - docker run -it --entrypoint=bash -v `pwd`:/root/tmp --rm macacajs/macaca-electron-docker-ubuntu -c "cd /root/tmp && npm run test ; cat ./coverage/lcov.info | coveralls"
